# Generated by Django 5.0.7 on 2024-08-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_marca_alter_carro_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_foto',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
