# Generated by Django 5.0.7 on 2024-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_carro_carro_foto_carro_placa'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='carro_obs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
