# Generated by Django 5.0.7 on 2024-08-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carro_placa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='carro_obs',
        ),
        migrations.AlterField(
            model_name='carro',
            name='placa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
