# Generated by Django 5.0.7 on 2025-01-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_carro_carro_obs_alter_carro_placa'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(max_length=60)),
                ('usuario_email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('usuario_senha', models.CharField(max_length=30)),
                ('usuario_quando', models.DateTimeField()),
            ],
        ),
    ]
