# Generated by Django 5.0.7 on 2025-01-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
