# Generated by Django 5.0.7 on 2025-01-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_quando',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_senha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
