# Generated by Django 5.0.7 on 2025-01-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_alter_usuario_usuario_nome_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
