# Generated by Django 5.0.7 on 2025-01-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('usuario_nome', models.CharField(blank=True, max_length=60, null=True)),
                ('usuario_email', models.EmailField(blank=True, max_length=60, null=True, unique=True)),
                ('usuario_senha', models.CharField(blank=True, max_length=30, null=True)),
                ('usuario_quando', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
