# Generated by Django 5.0.7 on 2025-01-23 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_cpf',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
