# Generated by Django 5.0.7 on 2025-01-23 20:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_usuario_usuario_cpf_alter_usuario_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario_quando',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
