# Generated by Django 5.0.7 on 2025-05-28 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_count', models.IntegerField()),
                ('car_value', models.FloatField()),
                ('car_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-car_date'],
            },
        ),
    ]
