# Generated by Django 5.2.1 on 2025-06-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_carro_carro_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='carro_obs',
        ),
    ]
